version: '{build}'
environment:
  USE_CLANG_COMPLETER: false
  COVERAGE: false
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    arch: 64
    python: 37
install:
  - ci\appveyor\appveyor_install.bat
build_script:
  - ci\appveyor\appveyor_build.bat
after_build:
  - if %COVERAGE% == true ( codecov )
# Disable automatic tests
test: off
cache:
  - '%LOCALAPPDATA%\pip\cache'  # Python packages from pip
  - '%APPDATA%\npm-cache'  # Node packages from npm
  - '%APPVEYOR_BUILD_FOLDER%\clang_archives'  # Clang downloads
     # jdt.ls download
  - '%APPVEYOR_BUILD_FOLDER%\third_party\eclipse.jdt.ls\target\cache'
  - '%APPVEYOR_BUILD_FOLDER%\third_party\clangd\cache'
