version: '{build}'
environment:
  USE_CLANG_COMPLETER: true
  COVERAGE: true
  matrix:
      #  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      #    arch: 64
      #    python: 37
      #  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      #    arch: 32
      #    python: 37
      #  # We only test Python 2.7 with MSVC 15 on 64-bit.
      #  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      #    arch: 64
      #    python: 27
      #  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      #    arch: 64
      #    python: 37
      #  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      #    arch: 64
      #    python: 37
      #    YCM_BENCHMARK: true
      #    COVERAGE: false
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    arch: 32
    python: 37
    YCM_PACKAGE: true
    COVERAGE: false
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    arch: 64
    python: 37
    YCM_PACKAGE: true
    COVERAGE: false
for:
  -
    matrix:
      only:
        - APPVEYOR_REPO_TAG_NAME: dev
    skip_tags: true
install:
  - ci\appveyor\appveyor_install.bat
build_script:
  - ci\appveyor\appveyor_build.bat
after_build:
  - if %COVERAGE% == true ( codecov )
  - ci\appveyor\appveyor_package.bat
deploy:
  - provider: GitHub
    auth_token:
      secure: B5NBpVx7OIYAAGGtzztXKNmx55oWDwLTcSuG7mq6M1r9NVWGQFWOoO16s7r7zdHR
    tag: dev
    release: ycmd $(YCMD_VERSION)
    description: ycmd development package
    artifact: ycmd
    draft: false
    prerelease: true
    force_update: true
    on:
      branch: release
      YCM_PACKAGE: true
      APPVEYOR_REPO_TAG: false
  - provider: GitHub
    auth_token:
      secure: B5NBpVx7OIYAAGGtzztXKNmx55oWDwLTcSuG7mq6M1r9NVWGQFWOoO16s7r7zdHR
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: ycmd $(APPVEYOR_REPO_TAG_NAME)
    description: ycmd release package
    artifact: ycmd
    draft: false
    force_update: true
    on:
      YCM_PACKAGE: true
      APPVEYOR_REPO_TAG: true
# Disable automatic tests
test: off
cache:
  - '%LOCALAPPDATA%\pip\cache'  # Python packages from pip
  - '%APPDATA%\npm-cache'  # Node packages from npm
  - '%USERPROFILE%\.cargo'  # Cargo package deps
  - '%APPVEYOR_BUILD_FOLDER%\clang_archives'  # Clang downloads
  - '%APPVEYOR_BUILD_FOLDER%\third_party\racerd\target'  # Racerd compilation
     # jdt.ls download
  - '%APPVEYOR_BUILD_FOLDER%\third_party\eclipse.jdt.ls\target\cache'
  - '%APPVEYOR_BUILD_FOLDER%\third_party\clangd\cache'
